---

- name: Install the systemd unit for synchronization
  copy:
    src: ops-registry-secret-sync.service
    dest: /etc/systemd/system/ops-registry-secret-sync.service
    owner: root
    group: root
    mode: 0644

- name: Install the script called by the systemd unit
  copy:
    src: ops-registry-secret-sync.sh
    dest: /usr/local/bin/ops-registry-secret-sync.sh
    owner: root
    group: root
    mode: 0755

- name: Enable the service
  systemd:
    name: ops-registry-secret-sync.service
    daemon_reload: yes
    enabled: yes
    masked: no

# The service starts Before=atomic-openshift-node. It will start
# automatically when the AMI boots. There is no reason to start
# it while the AMI is building.
