---
parent: 'test_cases/test_branch_openshift_ansible_logging_json_file_311.yml'
overrides:
  sync:
    - "openshift,origin=release-3.11"
    - "openshift,aos-cd-jobs=master"
    - "openshift,image-registry=release-3.11"
    - "openshift,openshift-ansible=release-3.11"
    - "openshift,kubernetes-metrics-server=release-3.11"
    - "openshift,origin-web-console-server=release-3.11"
