---
galaxy_info:
  author: Openshift Operations
  description: Install a systemd unit to keep the operations registry credentials synchronized and available on a cluster node.
  company: Red Hat
  license: Apache 2.0
  min_ansible_version: 1.9.2
  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - all
  categories:
  - system
dependencies:
